const SUBMIT_POST_FORM_REQUEST = "SUBMIT_POST_FORM_REQUEST";
const SUBMIT_POST_FORM_REQUEST_SUCCESS = "SUBMIT_POST_FORM_REQUEST_SUCCESS";
const SUBMIT_POST_FORM_REQUEST_FAILURE = "SUBMIT_POST_FORM_REQUEST_FAILURE";

export { SUBMIT_POST_FORM_REQUEST, SUBMIT_POST_FORM_REQUEST_SUCCESS, SUBMIT_POST_FORM_REQUEST_FAILURE }